### ISSUE TITLE
38: SyntaxWarning: "is not" with a literal. Did you mean "!="?   if parser.type() is not 'unknown':

### ISSUE THREAD

**Issue by startergo** [theopolis/uefi-firmware-parser#95]
```
uefi-firmware-parser --test ~/Downloads/*
/usr/local/bin/uefi-firmware-parser:38: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if parser.type() is not 'unknown':
/usr/local/bin/uefi-firmware-parser:141: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if parser.type() is 'unknown':
```

**Comment by startergo** [comment]
```
uefi-firmware-parser --superbrute /Users/g5/Downloads/MP51_007F_03B_LOCKED.bin
/usr/local/bin/uefi-firmware-parser:38: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if parser.type() is not 'unknown':
/usr/local/bin/uefi-firmware-parser:141: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if parser.type() is 'unknown':
Traceback (most recent call last):
  File "/usr/local/bin/uefi-firmware-parser", line 128, in <module>
    superbrute_search(input_data)
  File "/usr/local/bin/uefi-firmware-parser", line 36, in superbrute_search
    bdata = buffer(data, i)
NameError: name 'buffer' is not defined
```
